### ISSUE TITLE
Writable files?

### ISSUE THREAD

**Issue by PaulKinlan** [WICG/file-handling#1]
Would this also hook-up well with any of the Writable File specs that we are also working on? 

When Ben Well's and I were working on Web Intents, this was a common use-case he had: open a file edit it and then save it back to the OS. It's unclear to me if we would be able to solve that use-case in this spec.

**Comment by raymeskhoury** [comment]
I think the goal of this spec was to be able to edit files and save back to them as well. Is that correct @ewilligers ?

**Comment by ewilligers** [comment]
Yes, being able to write to files is the intention.

Hence the explainer uses [FileSystemFileHandle](https://github.com/WICG/writable-files/blob/master/EXPLAINER.md) instead of File, which would have given us the semantics of read-only copies.

**Comment by fallaciousreasoning** [comment]
The intention is to build this on top of [native-filesystem](https://github.com/WICG/native-file-system/blob/master/EXPLAINER.md), so this is definitely the intention.

Closing this as resolved.
