### ISSUE TITLE
Which ServiceWorker should be chosen if there is more than one available?

### ISSUE THREAD

**Issue by fallaciousreasoning** [WICG/file-handling#10]
An application can potentially have multiple service workers installed under its scope, which makes it difficult to determine which worker should receive the launch event. For example:

`app.com/sw-top.js`<br>
`app.com/pwa/manifest.json` ⇐ App scope, controlled by sw-top.js<br>
`app.com/pwa/sub-app/sw-sub-app.js` <br>
`app.com/pwa/sub-app/subber-app/sw-subber-app.js`

There are two solutions which are being considered for this problem:
1. Use whichever service worker manages the launch url for the app
2. Allow an `open_url` to be specified in the file handlers. The service worker that manages `open_url` will receive the launch event. This could be extended to allow specifying an open url per file handler.

Of the two, we're currently leaning towards 1), as it feel more natural (it’s also very similar to what we do in the PWA installability check). In addition, we might not know that there is a ServiceWorker available form `open_url` in 2) unless we have already visited the page.

**Comment by inexorabletash** [comment]
(1) seems like a good place to start. It seems like functionality akin to (2) can be added later on top of that if we nail down use cases that demand it.
