### ISSUE TITLE
Should the accept list be shared between Web Share Target V2 and file handling?

### ISSUE THREAD

**Issue by kenchris** [WICG/file-handling#2]
They will most likely contain the same list as the app/site is able to handle the same mime types/files, so does it really make sense that these are duplicated? @mgiuca

**Comment by ewilligers** [comment]
The extension mapping discussed in https://github.com/WICG/web-share-target/issues/74 could perhaps move to the top level of the manifest. Then only the list of MIME types would be listed twice. A web app might support only sharing or only file handing, so some repetition would be unavoidable.

**Comment by aarongustafson** [comment]
That was my thought as well. For example: a text composition app (Word, Docs, etc.) might exist as a handler to open a particular file type, but also accept sharing of images, videos, etc. into the currently open document. Combining the lists would make drawing that distinction potentially challenging (especially if you support a bunch of file formats in varying scenarios).

**Comment by fallaciousreasoning** [comment]
I tend to agree, it seems like there needs to be some kind of duplication to enable all use cases. Shall we close this issue?
