### ISSUE TITLE
Permission prompt needs to appear somewhere in the system

### ISSUE THREAD

**Issue by mgiuca** [WICG/file-handling#35]
@dbaron: from https://github.com/w3ctag/design-reviews/issues/371#issuecomment-530173327

> Another question is that of permissions. It seems like at some point the browser probably wants to ask the user for permission as to whether they want this particular installed web application to be able to access a particular file on the native file system. At the very least, it seems like a risk if there's no permission prompt anywhere in the system -- and it it at least seems like it might be easier to explain that stuff to users at use time rather than at registration time (since it's not clear that it's easy to explain to a user what a `application/foo` file is). This leads me to two thoughts:
>
> ...
>
> it's a little concerning that there doesn't appear to be asynchronous stuff in the explainer that gives a UA that wants to prompt the user for permission to have an opportunity to do so. Perhaps that's OK because the native file system API is sufficiently asynchronous to give the UA a chance to ask for permission through its API surface -- but it would be good to see examples in the explainer that show at what points a UA might choose to ask the user for permission.

Filing a separate bug to consider this. Probably just needs a non-normative recommendation to implementors in a security/privacy considerations section.

**Comment by fallaciousreasoning** [comment]
At the moment, before we allow a web app to open a directory, we show this prompt:
![Screenshot_20191203_105323](https://user-images.githubusercontent.com/7678024/70004651-290ce500-15bb-11ea-921e-c83ab7162a0c.png)

We could do something similar with file handling (presumably before pushing something to the launch queue).

**Comment by alice** [comment]
Back-linking this to TAG review https://github.com/w3ctag/design-reviews/issues/371

**Comment by dway123** [comment]
We've ended up incorporating this into our [security model](https://docs.google.com/document/d/1pTTO5MTSlxuqxpWL3pFblKB8y8SR0jPao8uAjJSUTp4/edit), and discussing a bit more in an [internal permissions doc](https://docs.google.com/document/d/1l00XFhWNA52LMKyK9XVE7tX0KAZZH80Eb1GNNP0NZWg/).

The explainer should probably still discuss a permission though...

**Comment by dway123** [comment]
Marking this as closed per the commit "mention permissions api integration"
