### ISSUE TITLE
Discuss integration with OS choosers

### ISSUE THREAD

**Issue by mgiuca** [WICG/file-handling#37]
We should present an analysis of how file handling is expected to be integrated with each major host OS (both from a technical standpoint, and UI). Similar to the [host platforms](https://github.com/WICG/badging/blob/master/docs/implementation.md) doc we did for Badging.

We should look at:

- Windows
- macOS
- Linux
- Chrome OS (for us on the Chrome OS team)
- Android (?)
- iOS (?)

And specifically:

- What technique the browser can use to integrate the web handler with the OS (e.g., associating with the browser binary in the system registry).
- What the UI looks like for the user to choose a file handler in the OS menu.
- Edge cases such as whether the OS automatically makes the handler the default if there are no other handlers (which should not be automatically done without user consent for web handlers, and could require an extra prompt).

**Comment by alice** [comment]
Back-linking this to TAG review https://github.com/w3ctag/design-reviews/issues/371
