### ISSUE TITLE
Treat "action" as a URL

### ISSUE THREAD

**Issue by alancutter** [WICG/file-handling#38]
The action field is specified as a partial URL, `"action": "/open-svg"`, something to concatenate with the origin `{origin}{action}`.

I think, given that it's ultimately a URL, it should be handled like all the other URLs in the manifest for consistency e.g. start_url, scope, icon src. These URLs are either absolute or relative to the manifest's parent URL.

**Comment by mgiuca** [comment]
I thought it was implied that that's how it would be interpreted (will be clearer in the spec, obviously).

But to make it explicit, here is a small fix to the explainer text.
