### ISSUE TITLE
Why does launch params have a list of files?

### ISSUE THREAD

**Issue by fallaciousreasoning** [WICG/file-handling#40]
@michaelwasserman brought up the good point that having a list of files in each launch params is a bit unnecessary: We could just add a separate LaunchParams item for each thing in the queue.

Note: This will make things more difficult for some of the System Web Apps teams experimenting with the API behind a flag in Chrome. I don't think this should be a real concern though @mgiuca

**Comment by michaelwasserman** [comment]
I think @mgiuca mentioned that there might be some apps that would handle groups of files opened together differently from a list of individual files opened separately. So I can see some value in keeping a list of files as a valid launch params entry.

**Comment by mgiuca** [comment]
Yeah, that was my one concern.

I'm not sure if it's ever necessary to distinguish those cases though. Does an app ever need to know whether it got opened with 5 files at the same time, or 5 files one file at a time? If the answer is "no", and I suspect it is, we should just flatten the queue-of-lists into a single queue.

**Comment by fallaciousreasoning** [comment]
Even if they do, it seems like it would be possible to hack around (e.g. by debouncing their launch queue consumer).

**Comment by evanstade** [comment]
I do believe certain apps want to make this distinction. For example, a zip archiving app probably wants to zip N files per single launch.
