### ISSUE TITLE
Integration with declarative link capturing?

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/file-handling#53]
Since this API provides a way to "launch" a PWA, and declarative link capturing provides a way for a website to specify what should happen when a PWA is launched, these two should probably be integrated in some way? I.e. opening the file in an existing window vs opening a new window for the file being opened. Any plans around that?

**Comment by mgiuca** [comment]
They were designed together and that's why File Handling has the concept of a launch queue. Not sure if the FH explainer references link capturing, but the DLC explainer [goes into detail on this relationship](https://github.com/WICG/sw-launch/blob/main/declarative_link_capturing.md#file-handling).

**Comment by alancutter** [comment]
The launch_handler [explainer](https://github.com/WICG/sw-launch/blob/main/launch_handler.md) aims to do just this.
