### ISSUE TITLE
File Handling Launch Destination on Chrome OS

### ISSUE THREAD

**Issue by Offroaders123** [WICG/file-handling#69]
I wasn't sure if this is intended behavior, as it only happens on Chrome OS. I found out that opening files from the file system in my PWA, using the File Handling API, a new PWA window is created every time, but inside of a new browser window tab, not a standalone PWA window. Is it required to use the Declarative Link Capturing API to get the original behavior of opening the new window in standalone mode? This is still the case on other platforms, and this difference only happens on Chrome OS for me.

**Comment by tomayac** [comment]
The behavior you see is temporary. In the mid-term [`"launch_handler"`](https://github.com/WICG/sw-launch/blob/main/launch_handler.md) will allow you to specify what should happen. The declarative link capturing feature will _not_ launch, see https://github.com/GoogleChrome/web.dev/pull/6863 for details.

**Comment by Offroaders123** [comment]
Thanks! I thought this was the case, since it is a pretty new API. Thought I'd mention it just in case it wasn't already known about 👍

**Comment by evanstade** [comment]
I think this was a bug that should be fixed now.
