### ISSUE TITLE
Detect PWA is default app for file handling

### ISSUE THREAD

**Issue by NhutTran98** [WICG/file-handling#76]
I want to know if user already set my PWA app as default file handler for specific file type (ex: application/pdf). Does anyone has a solution or can we add another param into `launchParams`.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/114656513/192999135-45d0d7c2-7fef-4594-8379-17e18696207e.png">

**Comment by tomayac** [comment]
Obtaining this information is currently not possible with the given API. What would be the use case for you to know this?

**Comment by NhutTran98** [comment]
@tomayac we need to track how many people make our app as default app for file handler.

**Comment by tomayac** [comment]
Unfortunately _"we need to track"_ is not a very convincing use case. Quite the opposite: someone having or not set your app to be a default file handler is another bit of entropy, so from a privacy perspective it's something that is not wanted—unless there is a very clear use case for why the benefits might outweigh the privacy issues.

**Comment by NhutTran98** [comment]
@tomayac Thank you for your response
