### ISSUE TITLE
Open With return an error

### ISSUE THREAD

**Issue by NhutTran98** [WICG/file-handling#77]
I am using `Open With` for opening pdf file in my PWA app. Sometime I don't know why when I open a file it return an error `Not allowed to open file` but when I try open again 2 to 3 times in the same file it work normally. Does anyone know why?

**Comment by fallaciousreasoning** [comment]
I think that some directories/types of files are considered sensitive & the browser won't allow you to open them.

**Comment by NhutTran98** [comment]
I don't think my files are considered sensitive because when I try open again from 2 to 3 times it works normally.

**Comment by fallaciousreasoning** [comment]
Hmm, interesting. In that case, it sounds like a browser specific bug. Would you mind filing a bug against Chromium here:
https://bugs.chromium.org/p/chromium/issues/entry?template=Defect+report+from+user

Add the following components:
`Blink>Storage>FileSystem`, `UI>Browser>WebAppInstalls>FileHandling`

and if you can, provide steps to reproduce. Thanks!
