### ISSUE TITLE
Support for mobile devices (Android/iOS)

### ISSUE THREAD

**Issue by HJunyuan** [WICG/file-handling#79]
While reading the capabilities outlined in the documentation for [letting installed web applications be file handlers](https://developer.chrome.com/docs/capabilities/web-apis/file-handling#feature_detection), I observed the following note:

> **Note**: File Handling is currently limited to desktop operating systems.

I am curious if there are any plans to extend support of file handling to installed PWAs on mobile devices, such as Android/iOS? If not, what are the challenges or roadblocks preventing this possibility?

**Comment by tomayac** [comment]
Not an immediate answer, but the closest to the File Handling experience on Android is to implement Web Share Target. This way, in the Files app, you can share a file, and your PWA would appear as one of the options to share the file to. 

Android doesn't support the File System Access API either, albeit we know it's a [popular feature request](https://crbug.com/1011535). To be fair, this API is not a strict pre-requirement for File Handling.

Maybe @evanstade can add more background?

**Comment by evanstade** [comment]
Since this is a question about whether Chromium implements the API on all platforms, and not something related to the API itself, see crbug.com/1403293
